[package]
name = "rust-kernel-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bitflags = "1.0"
volatile-register = "0.2"
spin = "*"
num_enum = {version = "*", default-features = false}
log = "0.4"

[profile.dev]
opt-level = 0
lto = false
panic = "abort"