[workspace]
members = [
	"kernel_io",
	"kernel_as_register",
	"kernel_error_macro",
	"kernel_lock",
	"kernel_as_register_macro",
	"kernel_main",
	"kernel_api",
	"kernel_syscall_abi",
	"to_trait",
	"to_trait_macro",
]