[package]
name = "to_trait_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
[dependencies]
syn = { version = "1.0.86", features = ["parsing"] }
quote = "*"
proc-macro2 = "*"